### ISSUE TITLE
Implement lastb?

### ISSUE THREAD

**Issue by nc7s** [thkukuk/wtmpdb#16]
> lastb is the same as last, except that by default it shows a log of the /var/log/btmp file, which contains all the bad login attempts.
[man page](https://manpages.debian.org/bookworm/util-linux/lastb.1.en.html)

This is pretty useful for security audit, for example.

I'm willing to implement it. Though it might be a bit hard for a PAM module to record the final result _after_ the PAM process..

**Comment by thkukuk** [comment]
The majority of applications do not support lastb, neither today nor in the past. Which means the current lastb output is pretty useless and not usable for a security audit.
For a security audit there is the audit framework.
And since there is no connection between wtmp and lastb, I did not implement it in wtmpdb and have no plans for this.
If somebody really needs `lastb` support, I suggest an independent implementation optimized for the lastb usecase.
