### ISSUE TITLE
Add support for suspend / resume events, storing wall messages

### ISSUE THREAD

**Issue by axet** [thkukuk/wtmpdb#18]
Hello!

I've been working on util-linux last wall entry features described here: https://github.com/util-linux/util-linux/issues/2452

Are you interested in implementing those features in wtmpdb?

**Comment by thkukuk** [comment]
About wall messages: this is nothing you can implement in wtmpdb, because there is no wtmpdb process which could listen to broadcast messages and store them in the DB.
So either you need to create an independent service, which listens the whole time to broadcast messages and stores them in wtmpdb. Or you need to add support to every single application, which does a reboot and sends out broadcast messages, so that they do store them additional in wtmpdb.
Both can be done independent of this wtmpdb implementation. For the first case, you could create a PR for such a daemon/systemd service and I would look at, if that could be usefull or not. For the second case: this is complete independent of wtmpdb, this needs patches for all such applications.

For the uptime "problem":  The `uptime` command from coreutils tries to solve this and is most of the time wrong. The userland does not notice if the kernel does a suspend or hibernate. And even the kernel does not know if it get's suspended or not if it runs virtulized. So your main problem would be, that you does not get the informations you would need to calculate a better uptime.
The uptime command tries to solves this, but it is most of the time so wrong, that at least openSUSE plans to switch to the uptime command from procps-ng.

**Comment by axet** [comment]
As you can see I'm only talking about messages types which can be stored inside tmpdb.

Here are 3 features I'm talking about which can be supported by tmpdb or not:

1) storing wall messages.
2) strong suspend / resume events.
3) storing time sync events.

All those been explained in details in url above. But you are right, it can be implemented in tmpdb service, using tmpdb api / args / opts or using systemd. But that not the question right now.

I'm asking if you are interested in storing such information, which can help a lot in managing linux reboot related information?

**Comment by thkukuk** [comment]
Again, please read my comment: the problem is not in storing this information's, the problem is in getting notifications that such events did happen.
And, e.g. in the case of VMs, even the kernel does not get informed, how do you want to get the information as userland process, where no API exists to get notified?

Please do at first your homework and come back with an explanation, how you want to get this events. If you know that, we can discuss how and where to store them.
If the problems would be so simple to solve, you wouldn't have the need to come up with 5-11 year old URLs.
